name: Process Dividend Stocks CSV

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # schedule:
    # Run every day at 1:00 AM UTC
    # - cron: '0 1 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  process-csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Run CSV combining script
      run: |
        python scripts/combined_csv_advanced.py

    - name: Create zip file of outputs
      run: |
        # Create a directory for outputs if it doesn't exist
        mkdir -p outputs
        # Copy the combined CSV file to outputs directory
        cp CombinedDividendStocks_*.csv outputs/
        # Create a zip file
        cd outputs
        zip -r ../dividend-stocks-data.zip .
        cd ..

    - name: Upload zip as artifact
      uses: actions/upload-artifact@v4
      with:
        name: dividend-stocks-data
        path: dividend-stocks-data.zip
        retention-days: 7

    # - name: Commit and push if changes
    #   run: |
    #     git config --local user.email "action@github.com"
    #     git config --local user.name "GitHub Action"
    #     git add CombinedDividendStocks_*.csv
    #     git diff --quiet && git diff --staged --quiet || git commit -m "Update combined dividend stocks data [automated]"
    #     git push